application: ambient-stone-132623
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# - url: /favicon.ico
#   static_files: favicon.ico
#   upload: favicon.ico

# # handlers:
# # - url: /static
# #   static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"